<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Caixa Registradora</title>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
          padding-top: 70px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Star Coffe</a>
        </div>
        
      </div>
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <form class="form-inline" action="/registrar" method="post">
                    <div class="form-group">
                        <label>Café</label>
                        <select name="cafe" class="form-control"> 
                            <option value="expresso"> expresso </option>
                            <option value="longo"> longo </option>
                            <option value="duplo"> duplo </option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Quantidade</label>
                        <input type="text" name="quantidade" value="1" class="form-control" />
                    </div>

                    <button type="submit" class="btn btn-default">Registrar!</button>
                </form>

                <hr />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php $i = 1; ?>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Café</th>
                            <th>Quantidade</th>
                            <th>Valor</th>
                        </tr>
                    </thead>
                    <tbody>
                <?php foreach ($caixaRegistradora->getItens() as $item): ?>
                    <tr>
                        <td><?php echo $i++ ?></td>
                        <td><?php echo $item->getNome(); ?></td>
                        <td><?php echo $item->getQuantidade(); ?></td>
                        <td><?php echo $item->getValor(); ?></td>
                     </tr>
                <?php endforeach; ?>
                    </tbody>
                </table>
            
                <h1>Valor total: <?php echo $caixaRegistradora->total(); ?></h1>
            </div>
        </div>

    </div><!-- /.container -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>
<script src="/js/bootstrap.min.js"></script> 
</body>
</html>